version: '1.0'
services:
  pgsql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ymlesaux
      POSTGRES_PASSWORD: erimel9801
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
 #   networks:
 #     - postgres
    volumes:
      - /data:/var/lib/postgresql/data
  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4:latest
    depends_on:
      - pgsql
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DISABLE_POSTFIX: true
    ports:
      - '82:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
#    networks:
#      - postgres
    restart:
      unless-stopped

#networks:
#  postgres:
#    driver: bridge

volumes:
  pgsql:
  pgadmin:
  
  # L'accès à pgadmin est réalisé via "localhost:82"
  # L'adresse du serveur pgsql à configurer dans pgadmin est pgsql:5432
  #   pgsql est le nom du service dans le présent fichier, et 5432 le port paramétré dans ce même fichier
